export const DOM = {
  msg: "#msg",
  result: "#result",
  cfgJson: "#cfg_json",
  horizonDays: "#horizon_days",
  costMin: "#cost_min",
  costMax: "#cost_max",
  meatTypes: "#meat_types",
  scheduleWeekdayChecks: "#schedule_weekdays input[type=checkbox]",
  scheduleWeekdayHint: "#schedule_weekday_hint",
  noConsecutiveMeat: "#no_consecutive_meat",
  weeklyQuotaInputs: "#weekly_quota_table .quota",
  repeatLimitInputs: "#repeat_limits_table .repeat-limit",
  preferInventory: "#prefer_inventory",
  preferExpiry: "#prefer_expiry",
  ingredientSearch: "#ingredient_search",
  ingredientSuggest: "#ingredient_suggest",
  ingredientChips: "#ingredient_chips",
  dishSearch: "#dish_search",
  dishRoleFilter: "#dish_role_filter",
  dishSuggest: "#dish_suggest",
  excludeDishChips: "#exclude_dish_chips",
  includeDateInput: "#include_date_input",
  includeDateAdd: "#include_date_add",
  includeDateChips: "#include_date_chips",
  excludeDateInput: "#exclude_date_input",
  excludeDateAdd: "#exclude_date_add",
  excludeDateChips: "#exclude_date_chips",
  btnLoadDefaults: "#btn_load_defaults",
  btnApplyJson: "#btn_apply_json",
  btnValidate: "#btn_validate",
  btnPlan: "#btn_plan",
  btnExportExcel: "#btn_export_excel",
};
