export const DOM = {
  msg: "#msg",
  result: "#result",
  cfgJson: "#cfg_json",
  dbSummary: "#db_summary",
  horizonDays: "#horizon_days",
  defaultPeople: "#default_people",
  costMin: "#cost_min",
  costMax: "#cost_max",
  meatTypes: "#meat_types",
  scheduleWeekdayChecks: "#schedule_weekdays input[type=checkbox]",
  scheduleWeekdayHint: "#schedule_weekday_hint",
  noConsecutiveMeat: "#no_consecutive_meat",
  dailyRoleInputs: "#daily_role_counts_table .daily-role-count",
  weekdayRoleTable: "#weekday_role_counts_table",
  weekdayRoleTableBody: "#weekday_role_counts_table tbody",
  weekdayRoleInputs: "#weekday_role_counts_table .weekday-role-count",
  weekdayRoleAddSelect: "#weekday_role_add_select",
  weekdayRoleAdd: "#weekday_role_add",
  weeklyQuotaInputs: "#weekly_quota_table .quota",
  repeatLimitInputs: "#repeat_limits_table .repeat-limit",
  preferInventory: "#prefer_inventory",
  preferExpiry: "#prefer_expiry",
  ingredientSearch: "#ingredient_search",
  ingredientSuggest: "#ingredient_suggest",
  ingredientSelectedItems: "#ingredient_chips",
  dishSearch: "#dish_search",
  dishRoleFilter: "#dish_role_filter",
  dishSuggest: "#dish_suggest",
  excludeDishSelectedItems: "#exclude_dish_chips",
  allowedDishSearch: "#allowed_dish_search",
  allowedDishRoleFilter: "#allowed_dish_role_filter",
  allowedDishSuggest: "#allowed_dish_suggest",
  allowedDishWeekdayChecks: "#allowed_dish_weekday_picker input[type=checkbox]",
  allowedDishRules: "#allowed_dish_rules",
  allowedDishDbRulesBtn: "#allowed_dish_db_rules_btn",
  includeDateInput: "#include_date_input",
  includeDateAdd: "#include_date_add",
  includeDateSelectedItems: "#include_date_chips",
  excludeDateInput: "#exclude_date_input",
  excludeDateAdd: "#exclude_date_add",
  excludeDateSelectedItems: "#exclude_date_chips",
  btnLoadDefaults: "#btn_load_defaults",
  btnApplyJson: "#btn_apply_json",
  btnValidate: "#btn_validate",
  btnPlan: "#btn_plan",
  btnExportExcel: "#btn_export_excel",
};
